version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: Go_dev
    ports:
      - "5433:5432"    # HostPort:ContainerPort
    environment:
      POSTGRES_USER: GO_DEV
      POSTGRES_PASSWORD: GO_DEV
      POSTGRES_DB: GO_DEV
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: go_todo_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: GO_DEV
      DB_PASSWORD: GO_DEV
      DB_NAME: GO_DEV
    restart: always

volumes:
  postgres_data:
